GPX-567: Actions starten jeden Montag um 07:00
gepaplexx/ansible-role-pxe pull request #11
Opened 2023-01-10 13:30 UTC by sgartner03

GPX-567: Actions starten jeden Montag um 07:00

2023-01-10 14:19 UTC, Lucostus approved these changes
LGTM

2023-01-12 07:50 UTC, gattma requested changes

2023-01-12 07:50 UTC, gattma commented on .github/workflows/develop.yml
> +    - cron: "0 7 * * 1"
Den Schedule wieder entfernen. Es reicht wenn main automatisch läuft.

2023-01-12 07:50 UTC, gattma commented on .github/workflows/main.yml
> +    - cron: "0 7 * * 1"
Bitte Tag und Uhrzeit noch anpassen (0 0 * * 1).
Den release job unten bitte um if: ${{ github.event_name != 'schedule' }} erweitern, damit der nicht jedesmal ausgeführt wird.

2023-01-19 06:39 UTC, gattma approved these changes

2023-01-19 08:28 UTC, merged